/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f0xx.h>

int main(void)
{
	uint32_t index=0;

	//uint8_t pole[32] = {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};
	uint32_t sekvencia = 0b10101001110111011100101010000000;


	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;

	GPIOA->BSRR = (1<<5); // set

	while(1){

	for(index=0;index<32;index++){
		if ((sekvencia << index)&(0x80000000)){GPIOA->BSRR = (1<<5);}
		else {GPIOA->BRR = (1<<5);} //reset

		for (volatile uint32_t i = 0; i < 100000; i++) {}
	}
}
}

