/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32f0xx.h>

int main(void)
{
	volatile uint32_t i;

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;

	//GPIOA->BSRR = (1<<5); // set

	for(;;){
		GPIOA->ODR ^= (1<<5); // toggle
		for (i = 0; i < 100000; i++) {}
}
}
